### ISSUE TITLE
v1.10.4

### ISSUE THREAD

**Issue by wgalafassijr** [clonemeagain/osticket-plugin-mentioner#10]
Hi,

Can you please confirm if the plugin work on version v1.10.4? Also the plugin modifie the core of osticket?

Regards,
Wilson

**Comment by clonemeagain** [comment]
Hi Wilson, 

It makes no modifications to core, but I've not yet tested it with 10.4 yet. If you do, please let me know, thanks!

**Comment by wgalafassijr** [comment]
Hi,

Is working fine on 10.4.

Regards,
Wilson

**Comment by clonemeagain** [comment]
Ok great, thanks mate.

**Comment by wgalafassijr** [comment]
A note: when using @user works fine on tasks, but when i use #user i have error 500 on browser. Something not doing well in this case.
